"""add frontend profile and media schema

Revision ID: 20260606_0001
Revises: a6b1c1a4697d
Create Date: 2026-06-06
"""

from typing import Sequence, Union

from alembic import op

revision: str = '20260606_0001'
down_revision: Union[str, None] = 'a6b1c1a4697d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1
                FROM pg_type
                WHERE typname = 'mediakind'
            ) THEN
                CREATE TYPE mediakind AS ENUM ('avatar', 'profile_photo');
            ELSE
                ALTER TYPE mediakind ADD VALUE IF NOT EXISTS 'avatar';
                ALTER TYPE mediakind ADD VALUE IF NOT EXISTS 'profile_photo';
            END IF;
        END $$;
        """
    )

    op.execute(
        """
        CREATE TABLE IF NOT EXISTS media (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            created_at TIMESTAMPTZ NOT NULL,
            updated_at TIMESTAMPTZ NOT NULL,
            kind mediakind NULL,
            filename VARCHAR(255) NOT NULL,
            original_filename VARCHAR(255) NOT NULL,
            content_type VARCHAR(100),
            file_size INTEGER NOT NULL,
            url VARCHAR NOT NULL
        );
        """
    )

    op.execute(
        """
        ALTER TABLE profiles
            ADD COLUMN IF NOT EXISTS faculty_id INTEGER;
        """
    )
    op.execute(
        """
        ALTER TABLE profiles
            ADD COLUMN IF NOT EXISTS course INTEGER;
        """
    )
    op.execute(
        """
        ALTER TABLE profiles
            ADD COLUMN IF NOT EXISTS city VARCHAR(100);
        """
    )
    op.execute(
        """
        ALTER TABLE profiles
            ADD COLUMN IF NOT EXISTS profile_description VARCHAR;
        """
    )
    op.execute(
        """
        ALTER TABLE profiles
            ADD COLUMN IF NOT EXISTS avatar_url VARCHAR;
        """
    )
    op.execute(
        """
        ALTER TABLE profiles
            ADD COLUMN IF NOT EXISTS photo_urls VARCHAR[] NOT NULL DEFAULT '{}';
        """
    )

    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1
                FROM pg_constraint
                WHERE conname = 'fk_profiles_faculty_id_faculties'
            ) THEN
                ALTER TABLE profiles
                    ADD CONSTRAINT fk_profiles_faculty_id_faculties
                    FOREIGN KEY (faculty_id)
                    REFERENCES faculties(id);
            END IF;
        END $$;
        """
    )


def downgrade() -> None:
    op.execute(
        """
        ALTER TABLE profiles
            DROP CONSTRAINT IF EXISTS fk_profiles_faculty_id_faculties;
        """
    )
    op.execute('ALTER TABLE profiles DROP COLUMN IF EXISTS profile_description;')
    op.execute('ALTER TABLE profiles DROP COLUMN IF EXISTS city;')
    op.execute('ALTER TABLE profiles DROP COLUMN IF EXISTS course;')
    op.execute('ALTER TABLE profiles DROP COLUMN IF EXISTS faculty_id;')
    op.execute('DROP TABLE IF EXISTS media;')