"""add onboarding fields to profiles

Revision ID: db73bcaa2d08
Revises: 95f39cef3923
Create Date: 2026-04-22 12:38:06.731108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db73bcaa2d08'
down_revision: Union[str, Sequence[str], None] = '95f39cef3923'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('sleep_schedule', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('profiles', sa.Column('cleanliness', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('profiles', sa.Column('noise_level', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('profiles', sa.Column('guest_frequency', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('profiles', sa.Column('smoking_preference', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('profiles', sa.Column('alcohol_preference', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('profiles', sa.Column('room_order_preference', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True))
    op.add_column('profiles', sa.Column('pet_preference', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('profiles', sa.Column('has_quiet_hours', sa.Boolean(), nullable=False))
    op.add_column('profiles', sa.Column('quiet_from', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True))
    op.add_column('profiles', sa.Column('quiet_to', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True))
    op.add_column('profiles', sa.Column('is_smoking_allowed', sa.Boolean(), nullable=False))
    op.add_column('profiles', sa.Column('has_pets', sa.Boolean(), nullable=False))
    op.add_column('profiles', sa.Column('budget_min', sa.Integer(), nullable=True))
    op.add_column('profiles', sa.Column('budget_max', sa.Integer(), nullable=True))
    op.add_column('profiles', sa.Column('move_in_date', sa.Date(), nullable=True))
    op.add_column('profiles', sa.Column('stay_duration', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('profiles', sa.Column('housing_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('profiles', sa.Column('living_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('profiles', sa.Column('ideal_roommate_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('profiles', sa.Column('rental_criteria', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('profiles', sa.Column('interests', postgresql.ARRAY(sa.String()), nullable=False))
    op.add_column('profiles', sa.Column('compatibility_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'compatibility_note')
    op.drop_column('profiles', 'interests')
    op.drop_column('profiles', 'rental_criteria')
    op.drop_column('profiles', 'ideal_roommate_description')
    op.drop_column('profiles', 'living_notes')
    op.drop_column('profiles', 'housing_type')
    op.drop_column('profiles', 'stay_duration')
    op.drop_column('profiles', 'move_in_date')
    op.drop_column('profiles', 'budget_max')
    op.drop_column('profiles', 'budget_min')
    op.drop_column('profiles', 'has_pets')
    op.drop_column('profiles', 'is_smoking_allowed')
    op.drop_column('profiles', 'quiet_to')
    op.drop_column('profiles', 'quiet_from')
    op.drop_column('profiles', 'has_quiet_hours')
    op.drop_column('profiles', 'pet_preference')
    op.drop_column('profiles', 'room_order_preference')
    op.drop_column('profiles', 'alcohol_preference')
    op.drop_column('profiles', 'smoking_preference')
    op.drop_column('profiles', 'guest_frequency')
    op.drop_column('profiles', 'noise_level')
    op.drop_column('profiles', 'cleanliness')
    op.drop_column('profiles', 'sleep_schedule')
    # ### end Alembic commands ###