from .chats import ChatModel
from .complaints import ComplaintModel
from .deals import DealModel
from .dorms import DormModel
from .faculties import FacultyModel
from .messages import MessageModel
from .neighbourhoods import NeighbourhoodModel
from .profiles import ProfileModel
from .reactions import ReactionModel
from .tags import TagModel
from .tags import ProfileTagLink
from .universities import UniversityModel
from .users import UserModel
