from .users import *
from .complaints import *
from .profiles import *
from .dislikes import *
from .likes import *
from .tags import *
from .universities import *
from .dorms import *
from .messages import *
from .chats import *
from .deals import *
from .neighbourhoods import *
